- id: wasmachine_cyclus_gestart
  alias: Wasmachine cyclus gestart
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.wasmachine_aan
      to: "on"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.wasmachine_heeft_gedraaid

- id: wasmachine_klaar
  alias: Wasmachine klaar
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.wasmachine_aan
      to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.wasmachine_heeft_gedraaid
      state: "on"
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.wasmachine_laag_verbruik
          to: "on"
      timeout: "00:30:00"
      continue_on_timeout: false

    - condition: state
      entity_id: binary_sensor.wasmachine_aan
      state: "off"

    - service: notify.mobile_app_iphone_15_pro_max
      data:
        title: "✅ Wasmachine klaar"
        message: "Klaar om {{ now().strftime('%H:%M') }}."

    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.wasmachine_heeft_gedraaid

- id: droger_cyclus_gestart
  alias: Droger cyclus gestart
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.droger_aan
      to: "on"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.droger_heeft_gedraaid

- id: droger_klaar
  alias: Droger klaar
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.droger_aan
      to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.droger_heeft_gedraaid
      state: "on"
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.droger_laag_verbruik
          to: "on"
      timeout: "00:30:00"
      continue_on_timeout: false

    - condition: state
      entity_id: binary_sensor.droger_aan
      state: "off"

    - service: notify.mobile_app_iphone_15_pro_max
      data:
        title: "✅ Droger klaar"
        message: "Klaar om {{ now().strftime('%H:%M') }}."

    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.droger_heeft_gedraaid