- id: overloop_motion_verlichting_on
  alias: Overloop - Motion verlichting on
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.overloop_motion
      to: "on"
      id: motion_on

  action:
    # Nieuwe motion = lopende nachttimer annuleren/resetten
    - service: timer.cancel
      target:
        entity_id: timer.overloop_nachtlamp_off

    # Nacht: badkamer + toilet alleen aanzetten als beide nog uit zijn
    - choose:
        - conditions:
            - condition: or
              conditions:
                - condition: time
                  after: "21:00:00"
                - condition: time
                  before: "07:00:00"
            - condition: state
              entity_id: light.toilet_boven
              state: "off"
            - condition: state
              entity_id: light.badkamer
              state: "off"
          sequence:
            - service: scene.turn_on
              target:
                entity_id:
                  - scene.toilet_boven_nachtlampje
                  - scene.badkamer_nachtlampje

            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.overloop_nachtlamp_actief

    # Ochtend: keuken alleen aanzetten als beide lampen uit zijn
    - choose:
        - conditions:
            - condition: time
              after: "06:00:00"
              before: "08:00:00"
            - condition: state
              entity_id: light.keuken_2
              state: "off"
            - condition: state
              entity_id: light.eethoek
              state: "off"
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.keuken_ochtend_15

- id: overloop_motion_verlichting_start_off_timer
  alias: Overloop - Motion verlichting start off timer
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.overloop_motion
      to: "off"

  condition:
    - condition: state
      entity_id: input_boolean.overloop_nachtlamp_actief
      state: "on"

  action:
    - service: timer.start
      target:
        entity_id: timer.overloop_nachtlamp_off
      data:
        duration: "00:15:00"

- id: overloop_motion_verlichting_timer_finished
  alias: Overloop - Motion verlichting timer finished
  mode: single
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.overloop_nachtlamp_off

  condition:
    - condition: state
      entity_id: input_boolean.overloop_nachtlamp_actief
      state: "on"

    - condition: state
      entity_id: binary_sensor.overloop_motion
      state: "off"

  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.toilet_boven
          - light.badkamer

    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.overloop_nachtlamp_actief