- platform: group
  name: Muurlampen
  unique_id: buiten_muurlampen
  entities:
    - light.muurlamp_1
    - light.muurlamp_2
    - light.muurlamp_3     
    - light.muurlamp_4
    - light.muurlamp_5
    - light.muurlamp_6     

- platform: group
  name: Tuin Lampen
  unique_id: tuin_lampen
  entities:
    - light.buiten
    - light.tuin_stopcontact_light