- id: hal_kast_aan_bij_deur_open
  alias: Hal kast aan bij deur open
  trigger:
    - platform: state
      entity_id: binary_sensor.deursensor
      to: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.hal_kast
  mode: single

- id: hal_kast_uit_bij_deur_dicht
  alias: Hal kast uit bij deur dicht
  trigger:
    - platform: state
      entity_id: binary_sensor.deursensor
      to: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.hal_kast
  mode: single

- id: deurbel_toon_live_view_30s # optioneel maar handig
  alias: Deurbel - toon live view 30s
  mode: restart
  trigger:
    - platform: event
      event_type: state_changed
      event_data:
        entity_id: event.voordeur_ding
  condition:
    # Alleen bij een echte ding (en niet bij HA start)
    - condition: template
      value_template: >
        {{ trigger.event.data.new_state is not none
           and trigger.event.data.new_state.attributes.event_type == 'ding' }}
  action:
    - service: timer.start
      target:
        entity_id: timer.deurbel_weergave
      data:
        duration: "00:00:30"
