template: !include ../package_areas/jesse/templates.yaml
input_boolean: !include ../package_areas/jesse/input_booleans.yaml
input_text: !include ../package_areas/jesse/input_texts.yaml
input_datetime: !include ../package_areas/jesse/input_datetimes.yaml
script: !include ../package_areas/jesse/scripts.yaml
switch: !include ../package_areas/jesse/switches.yaml
automation: !include ../package_areas/jesse/automations.yaml