cover: !include ../package_areas/kantoor/covers.yaml
input_boolean: !include ../package_areas/kantoor/input_booleans.yaml
template: !include ../package_areas/kantoor/templates.yaml
light: !include ../package_areas/kantoor/lights.yaml
automation: !include ../package_areas/kantoor/automations.yaml